FROM openjdk:17-jdk-alpine as builder

WORKDIR /app/msvc-courses

COPY ./pom.xml /app
COPY ./msvc-courses/.mvn ./.mvn
COPY ./msvc-courses/mvnw .
COPY ./msvc-courses/pom.xml .

RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/
COPY ./msvc-courses/src ./src
RUN ./mvnw clean package -DskipTests

FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/msvc-courses/target/msvc-courses.jar .
EXPOSE 8001
ENTRYPOINT ["java","-jar","msvc-courses.jar"]


# docker build -t msvc-courses . -f ./msvc-courses/Dockerfile-v3
# docker run -p 8002:8002 msvc-courses