FROM openjdk:17.0.2

WORKDIR /app/msvc-courses

COPY ./pom.xml /app
COPY ./msvc-courses/.mvn ./.mvn
COPY ./msvc-courses/mvnw .
COPY ./msvc-courses/pom.xml .

RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/

COPY ./msvc-courses/src ./src

RUN ./mvnw clean package -DskipTests

EXPOSE 8001
ENTRYPOINT ["java","-jar","./target/msvc-courses.jar"]


# docker build -t msvc-courses-2 . -f ./msvc-courses/Dockerfile-v2
# docker run -p 8001:8001 msvc-courses-2